ALTER TABLE TODOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE TODOS CASCADE CONSTRAINTS;

CREATE TABLE TODOS
(
  ID        INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) not null primary key,
  CREATED   TIMESTAMP(6)                        DEFAULT current_timestamp,
  DOCUMENT  VARCHAR2(32767 BYTE)
  CONSTRAINT todo_documentensure_json CHECK (document IS JSON)
);

