ALTER TABLE PLANAPP4.TODOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE PLANAPP4.TODOS CASCADE CONSTRAINTS;

CREATE TABLE PLANAPP4.TODOS
(
  ID        INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CREATED   TIMESTAMP(6)                        DEFAULT current_timestamp,
  DOCUMENT  VARCHAR2(32767 BYTE)
  CONSTRAINT todo_documentensure_json CHECK (document IS JSON)
);

